### ISSUE TITLE
Examples don't compile on 0.1.4 (master)

### ISSUE THREAD

**Issue by CyanBlob** [PradeepKumarRajamanickam/bevy_input_map#28]
I'm on commit af94de1612b06078420602ef2c75bdf9d2e26429

I cloned the repo, then tried running an example with:
```
cargo run --example keyboard_mouse_with_code
```
Output:
```
warning: unused manifest key: package.example
   Compiling bevy_prototype_input_map v0.1.3 (/home/andrew/Development/bevy_input_map)
error[E0277]: the trait bound `bevy::prelude::GamepadButtonType: axis::_::_serde::Serialize` is not satisfied
  --> src/serde.rs:49:5                       
   |
49 | /     #[serde(default, rename = "GamepadButtons")]
50 | |     gamepad_button_bindings: HashMap<usize, HashMap<GamepadButtonType, String>>,
   | |_______________________________________________________________________________^ the trait `axis::_::_serde::Serialize` is not implemented for `bevy::prelude::GamepadButtonType`
   |                                   
   = note: required because of the requirements on the impl of `axis::_::_serde::Serialize` for `std::collections::HashMap<bevy::prelude::GamepadButtonType, std::string::String>`
   = note: required because of the requirements on the impl of `axis::_::_serde::Serialize` for `std::collections::HashMap<usize, std::collections::HashMap<bevy::prelude::GamepadButtonType, std::string::String>>`
   = note: required by `axis::_::_serde::ser::SerializeStruct::serialize_field`
                                                                               
error[E0277]: the trait bound `bevy::prelude::GamepadButtonType: Deserialize<'_>` is not satisfied
  --> src/serde.rs:49:5                                         
   |                                                
49 | /     #[serde(default, rename = "GamepadButtons")]
50 | |     gamepad_button_bindings: HashMap<usize, HashMap<GamepadButtonType, String>>,
   | |_______________________________________________________________________________^ the trait `Deserialize<'_>` is not implemented for `bevy::prelude::GamepadButtonType`
   |                                                             
   = note: required because of the requirements on the impl of `Deserialize<'_>` for `std::collections::HashMap<bevy::prelude::GamepadButtonType, std::string::String>`
   = note: required because of the requirements on the impl of `Deserialize<'_>` for `std::collections::HashMap<usize, std::collections::HashMap<bevy::prelude::GamepadButtonType, std::string::String>>`
   = note: required by `next_element`         
                                                                               
error[E0277]: the trait bound `bevy::prelude::GamepadButtonType: Deserialize<'_>` is not satisfied
  --> src/serde.rs:49:5                                     
   |                                                                      
49 | /     #[serde(default, rename = "GamepadButtons")]
50 | |     gamepad_button_bindings: HashMap<usize, HashMap<GamepadButtonType, String>>,
   | |_______________________________________________________________________________^ the trait `Deserialize<'_>` is not implemented for `bevy::prelude::GamepadButtonType`
   |                                                           
   = note: required because of the requirements on the impl of `Deserialize<'_>` for `std::collections::HashMap<bevy::prelude::GamepadButtonType, std::string::String>`
   = note: required because of the requirements on the impl of `Deserialize<'_>` for `std::collections::HashMap<usize, std::collections::HashMap<bevy::prelude::GamepadButtonType, std::string::String>>`
   = note: required by `next_value`                                   
                                                                               
error: aborting due to 3 previous errors                                
                                                                               
For more information about this error, try `rustc --explain E0277`.                                                                                            
error: could not compile `bevy_prototype_input_map`            
                                                                               
To learn more, run the command again with --verbose.
```

This is on Arch Linux, with Rust version `1.45.2`

**Comment by PradeepKumarRajamanickam** [comment]
This is a known issue. bevy_input has some unreleased changes on master that is required for gamepad support. You can refer wilsk's comment on how to workaround this issue with git
https://discord.com/channels/691052431525675048/745355529777315850/764406566786957322

the checkout for 0.1.4 is 8d66fb5 on release/v0.1.4 branch it is not part of master. Had to pull out some wip stuff inorder to release 0.1.4.

**Comment by PradeepKumarRajamanickam** [comment]
I am going to go ahead and close this ticket. Since this is expected at the moment. 

We can reopen it if it happens again after gamepad support is released.
